# Generated by Django 5.1.7 on 2025-05-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
