# Generated by Django 5.1.7 on 2025-05-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
