# Generated by Django 5.1.7 on 2025-05-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cart_is_accepted_cart_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_id',
        ),
    ]
