# Generated by Django 5.1.7 on 2025-06-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_cart_is_accepted_remove_cart_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], max_length=20, null=True),
        ),
    ]
